name: wire_example_shared
description: examples of shared code using git-subrepo
publish_to: 'none'
version: 0.0.3

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  wire: ^1.4.3
  hive: ^2.0.5
  path_provider:

dev_dependencies:

dependency_overrides:
#  Only for development in main wire repo
#  wire:
#    path: ../..
