name: wire_example_shared
description: examples of shared code using git-subrepo
version: 0.0.3
# publish_to: none

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  wire: ^1.4.7
  hive: ^2.0.5
  path_provider: ^2.0.8

dev_dependencies:

dependency_overrides:
#  Only for development in main wire repo
  wire:
    path: ../..
