name: wire_example_shared
description: examples of shared code using git-subrepo
version: 0.0.2
# publish_to: none

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  wire: ^1.2.0

dev_dependencies:

dependency_overrides:
#  Only for development in main wire repo
#  wire:
#    path: ../..
