name: wire_example_shared
description: examples shared code
version: 0.0.1
# publish_to: none

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  wire: ^1.1.0

dev_dependencies:

dependency_overrides:
#  Only for development in main wire repo
#  wire:
#    path: ../..
